### ISSUE TITLE
Comparison results of ssdeep vs. spamsum

### ISSUE THREAD

**Issue by ross-spencer** [michielbuddingh/spamsum#1] opened 2015-11-10 22:04 UTC
Hi, 

I'm interested in using your library in Golang and wanted to understand the differences between it and ssdeep.

i have a corpus of test objects described here in my overview: https://gist.github.com/ross-spencer/60c43abc87faa30ae7c3#file-ssdeep-spamsum-comparison-overview

And have found the following false results when comparing the output of SSDEEP vs. Spamsum: https://gist.github.com/ross-spencer/60c43abc87faa30ae7c3#file-false-results-csv 

316 match, vs. 9 that don't. 

Is it worth me looking at the spamsum code to try and improve the algorithm to match ssdeep - do you think ssdeep is a good benchmark? 

Edit: I've run a quick comparison of the strings, and they seem to be different in the same places: https://gist.github.com/ross-spencer/60c43abc87faa30ae7c3#file-comparison-of-differences-txt 

I will need to look at the one string that is completely different from the ssdeep output.

**Comment by michielbuddingh** [comment] 2015-11-11 20:00
Hi Ross,

First of all, let me thank you for taking the effort to perform a more comprehensive test of the code in this repository.  This kind of cross-checking is very valuable, even when it doesn't find bugs.  When it does, it's doubly so.

For the sake of clarity, let's differentiate between a few things called 'spamsum': there's Andrew Tridgell's original algorithm (called spamsum).  His original C implementation (let's refer to it as cspamsum), ssdeep, by Jesse Kornblum, which re-uses the code of cspamsum, and then there's my reimplementation in Go (let's call it gospamsum).

cspamsum isn't wrong (by definition).  ssdeep does not seem to differ from cspamsum.  gospamsum does, therefore it is buggy.

You are very welcome to improve gospamsum if you want to and can spare the time.  If you need any help, feel free to ask.  If you don't have the time, I'll make the effort to squash the bug myself; you've already done quite a bit of heavy lifting by testing the code and finding the bug; I can hardly ask for more.

**Comment by ross-spencer** [comment] 2015-11-17 09:06
Many thanks Michael.

I'm happy to look at it but it just might take some time for me to isolate it in trying to understand the algorithm.

I'm reading around the subject tonight and looking at the cspamsumcode too. Here: https://www.samba.org/ftp/unpacked/junkcode/spamsum/spamsum.c

I am trying to understand the three colon delineated segments. The first, block-size, the second, the spamsum string, the third ? 

Do I understand the second to be 64 characters per the source code? 

/\* the output is a string of length 64 in base64 */
#define SPAMSUM_LENGTH 64

If so, then two strings I'm looking at:

Gospamsum: 768:tlBecdq6/+dgZUTp+gAdA3T9Y02xEFshHOl3O98FzbXfBfhPcGxGB3whvm9HvMB:O

ssdeep: 768:tlBecdq6/+dgZUTp+gAdA3T9Y02xEFshHOl3O98FzbXfBfhPcGxGB3whvm9HvMB1:O

The second string: tlBecdq6/+dgZUTp+gAdA3T9Y02xEFshHOl3O98FzbXfBfhPcGxGB3whvm9HvMB1

Is 65 characters in ssdeep, and so I wonder if it is returning incorrectly for some reason? I've tried 2.7 and 2.13 so maybe a change was introduced before those? 

I'm using the file LAND,map from here: https://github.com/ross-spencer/opf-format-corpus/tree/master/format-corpus/pcraster

**Comment by michielbuddingh** [comment] 2018-03-27 16:16
I've fixed the bug in question and added two affected files from the opf format corpus as regression test cases.  Since I left this issue open for way too long, I'll close it now, but if this fix doesn't address your concerns, please feel free to open another one.

**Closed as completed by michielbuddingh** 2018-03-27 16:16 UTC
